"""Pydantic request/response models for VPN session endpoints."""

from __future__ import annotations

import base64
from datetime import datetime

from pydantic import BaseModel, field_validator


class SessionCreateRequest(BaseModel):
    """Request body for creating a new VPN session.

    Attributes:
        device_name: Human-readable name for the client device (1–100 chars).
        client_public_key: WireGuard public key generated by the client (base64, 44 chars).
    """

    device_name: str
    client_public_key: str

    @field_validator("device_name")
    @classmethod
    def validate_device_name(cls, value: str) -> str:
        """Ensure device name is within the allowed length."""
        stripped = value.strip()
        if not stripped or len(stripped) > 100:
            raise ValueError("device_name must be between 1 and 100 characters")
        return stripped

    @field_validator("client_public_key")
    @classmethod
    def validate_public_key(cls, value: str) -> str:
        """Validate WireGuard public key format (44-char base64 string)."""
        stripped = value.strip()
        if len(stripped) != 44:
            raise ValueError("client_public_key must be 44 characters (base64 WireGuard key)")
        try:
            decoded = base64.b64decode(stripped)
            if len(decoded) != 32:
                raise ValueError
        except Exception:
            raise ValueError("client_public_key is not valid base64")
        return stripped


class SessionCreateResponse(BaseModel):
    """Response body after successfully creating a VPN session.

    Attributes:
        session_id: UUID of the newly created session.
        server_public_key: Server's WireGuard public key for client tunnel config.
        server_endpoint: Public host:port for the client to connect to.
        assigned_ip: IP address assigned to this client (CIDR notation, e.g. 10.10.0.2/32).
        dns_servers: List of DNS server IPs to use inside the tunnel.
        allowed_ips: CIDR ranges to route through the tunnel (typically 0.0.0.0/0).
        expires_at: UTC timestamp when this session will expire.
        keepalive_interval: Recommended persistent keepalive interval in seconds.
    """

    session_id: str
    server_public_key: str
    server_endpoint: str
    assigned_ip: str
    dns_servers: list[str]
    allowed_ips: list[str]
    expires_at: datetime
    keepalive_interval: int


class SessionListItem(BaseModel):
    """Summary of a single VPN session, used in list responses.

    Attributes:
        session_id: UUID of the session.
        device_name: Name of the device associated with this session.
        assigned_ip: IP address assigned to this session (CIDR notation).
        status: Session state: 'active', 'expired', or 'revoked'.
        created_at: UTC timestamp when the session was created.
        expires_at: UTC timestamp when the session expires.
        last_handshake: UTC time of the last WireGuard handshake, or None.
    """

    session_id: str
    device_name: str
    assigned_ip: str
    status: str
    created_at: datetime
    expires_at: datetime
    last_handshake: datetime | None


class SessionListResponse(BaseModel):
    """Response body for listing sessions.

    Attributes:
        sessions: List of session summaries for the authenticated user.
    """

    sessions: list[SessionListItem]


class SessionDetailResponse(BaseModel):
    """Detailed response for a single VPN session.

    Attributes:
        session_id: UUID of the session.
        device_name: Name of the device associated with this session.
        client_public_key: WireGuard public key of the client.
        assigned_ip: IP address assigned to this session (CIDR notation).
        status: Session state: 'active', 'expired', or 'revoked'.
        created_at: UTC timestamp when the session was created.
        expires_at: UTC timestamp when the session expires.
        last_handshake: UTC time of the last WireGuard handshake, or None.
        transfer_rx: Bytes received through the tunnel.
        transfer_tx: Bytes sent through the tunnel.
    """

    session_id: str
    device_name: str
    client_public_key: str
    assigned_ip: str
    status: str
    created_at: datetime
    expires_at: datetime
    last_handshake: datetime | None
    transfer_rx: int
    transfer_tx: int


class SessionRevokeResponse(BaseModel):
    """Response body after revoking a session.

    Attributes:
        session_id: UUID of the revoked session.
        status: Always 'revoked'.
    """

    session_id: str
    status: str


class DeviceItem(BaseModel):
    """Summary of a registered device.

    Attributes:
        device_id: UUID of the device.
        name: Human-readable device name.
        public_key: WireGuard public key registered for this device.
        created_at: UTC timestamp when the device was first registered.
        last_active: UTC timestamp of the last active session, or None.
    """

    device_id: str
    name: str
    public_key: str
    created_at: datetime
    last_active: datetime | None


class DeviceListResponse(BaseModel):
    """Response body for listing devices.

    Attributes:
        devices: List of device summaries for the authenticated user.
    """

    devices: list[DeviceItem]


class HealthResponse(BaseModel):
    """Response body for the health check endpoint.

    Attributes:
        status: Service health state ('healthy').
        wireguard: WireGuard interface state ('up' or 'down').
        version: Application version string.
    """

    status: str
    wireguard: str
    version: str
