"""Business logic for VPN session lifecycle management."""

from __future__ import annotations

import ipaddress
import logging
from datetime import datetime, timedelta, timezone

from fastapi import HTTPException, status
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from vpnservice.config import Settings
from vpnservice.models import Device, SessionStatus, SystemSettings, User, VPNSession
from vpnservice.vpn.ip_allocator import allocate_ip
from vpnservice.vpn.schemas import (
    DeviceItem,
    DeviceListResponse,
    SessionCreateResponse,
    SessionDetailResponse,
    SessionListItem,
    SessionListResponse,
    SessionRevokeResponse,
)
from vpnservice.wireguard.manager import WireGuardError, WireGuardManager

logger = logging.getLogger(__name__)


async def _get_system_settings(db: AsyncSession) -> SystemSettings:
    """Load the singleton SystemSettings row, creating defaults if absent.

    Args:
        db: Active database session.

    Returns:
        SystemSettings instance with current configuration.
    """
    result = await db.execute(select(SystemSettings))
    settings_row = result.scalar_one_or_none()
    if settings_row is None:
        settings_row = SystemSettings(id=1)
        db.add(settings_row)
        await db.flush()
    return settings_row


async def create_session(
    user: User,
    device_name: str,
    client_public_key: str,
    db: AsyncSession,
    settings: Settings,
    wg_manager: WireGuardManager,
) -> SessionCreateResponse:
    """Create a new VPN session by registering a WireGuard peer.

    Validates the session limit, allocates an IP, creates or updates the Device
    record, adds the peer to WireGuard, and persists the VPNSession.

    Args:
        user: Authenticated user requesting the session.
        device_name: Human-readable name for the client device.
        client_public_key: WireGuard public key generated by the client.
        db: Active database session.
        settings: Application configuration.
        wg_manager: WireGuard manager instance.

    Returns:
        SessionCreateResponse containing tunnel configuration for the client.

    Raises:
        HTTPException 409: Session limit reached or public key already active.
        HTTPException 503: WireGuard interface unavailable.
    """
    sys_settings = await _get_system_settings(db)

    active_count_result = await db.execute(
        select(func.count(VPNSession.id)).where(
            VPNSession.user_id == user.id,
            VPNSession.status == SessionStatus.active,
        )
    )
    active_count: int = active_count_result.scalar_one()

    if active_count >= sys_settings.max_sessions_per_user:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                f"Session limit reached. Maximum {sys_settings.max_sessions_per_user} "
                f"active session(s) allowed. Revoke an existing session first."
            ),
        )

    existing_key_result = await db.execute(
        select(Device).where(Device.public_key == client_public_key)
    )
    existing_device = existing_key_result.scalar_one_or_none()
    if existing_device is not None:
        if existing_device.user_id != user.id:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Public key already registered to another user.",
            )
        active_session_result = await db.execute(
            select(VPNSession).where(
                VPNSession.device_id == existing_device.id,
                VPNSession.status == SessionStatus.active,
            )
        )
        if active_session_result.scalar_one_or_none() is not None:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="A device with this public key already has an active session.",
            )

    assigned_ip = await allocate_ip(db, settings)
    if assigned_ip is None:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="IP address pool exhausted. No available addresses.",
        )

    device = await _get_or_create_device(user, device_name, client_public_key, db)

    if not await wg_manager.is_available():
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="WireGuard interface is not available.",
        )

    try:
        await wg_manager.add_peer(client_public_key, assigned_ip)
    except WireGuardError as exc:
        logger.error("Failed to add WireGuard peer for user %s: %s", user.username, exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Failed to configure WireGuard peer.",
        )

    expires_at = datetime.now(tz=timezone.utc) + timedelta(hours=sys_settings.session_ttl_hours)

    session = VPNSession(
        user_id=user.id,
        device_id=device.id,
        assigned_ip=assigned_ip,
        status=SessionStatus.active,
        expires_at=expires_at,
    )
    db.add(session)

    device.last_active_at = datetime.now(tz=timezone.utc)
    await db.commit()
    await db.refresh(session)

    logger.info(
        "Created VPN session %s for user %s, device %s, ip %s",
        session.id, user.username, device_name, assigned_ip,
    )

    subnet = ipaddress.ip_network(settings.wg_subnet)
    server_ip = str(list(subnet.hosts())[0])

    return SessionCreateResponse(
        session_id=session.id,
        server_public_key=wg_manager.get_server_public_key(),
        server_endpoint=wg_manager.get_endpoint(),
        assigned_ip=assigned_ip,
        dns_servers=[server_ip],
        allowed_ips=["0.0.0.0/0"],
        expires_at=expires_at,
        keepalive_interval=25,
    )


async def list_sessions(
    user: User,
    db: AsyncSession,
    wg_manager: WireGuardManager,
) -> SessionListResponse:
    """Return all sessions for the authenticated user with live WireGuard stats.

    Args:
        user: Authenticated user whose sessions to retrieve.
        db: Active database session.
        wg_manager: WireGuard manager for live peer statistics.

    Returns:
        SessionListResponse containing all sessions regardless of status.
    """
    result = await db.execute(
        select(VPNSession, Device)
        .join(Device, VPNSession.device_id == Device.id)
        .where(VPNSession.user_id == user.id)
        .order_by(VPNSession.created_at.desc())
    )
    rows = result.all()

    peer_stats = {p.public_key: p for p in await wg_manager.list_peers()}

    items: list[SessionListItem] = []
    for vpn_session, device in rows:
        stats = peer_stats.get(device.public_key)
        items.append(SessionListItem(
            session_id=vpn_session.id,
            device_name=device.name,
            assigned_ip=vpn_session.assigned_ip,
            status=vpn_session.status.value,
            created_at=vpn_session.created_at,
            expires_at=vpn_session.expires_at,
            last_handshake=stats.last_handshake if stats else None,
        ))

    return SessionListResponse(sessions=items)


async def get_session(
    user: User,
    session_id: str,
    db: AsyncSession,
    wg_manager: WireGuardManager,
) -> SessionDetailResponse:
    """Retrieve detailed information for a specific session, including live stats.

    Args:
        user: Authenticated user (must own the session).
        session_id: UUID of the session to retrieve.
        db: Active database session.
        wg_manager: WireGuard manager for live peer statistics.

    Returns:
        SessionDetailResponse with transfer stats and last handshake time.

    Raises:
        HTTPException 404: Session not found or not owned by this user.
    """
    result = await db.execute(
        select(VPNSession, Device)
        .join(Device, VPNSession.device_id == Device.id)
        .where(VPNSession.id == session_id, VPNSession.user_id == user.id)
    )
    row = result.one_or_none()
    if row is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found.",
        )

    vpn_session, device = row
    stats = await wg_manager.get_peer_stats(device.public_key)

    return SessionDetailResponse(
        session_id=vpn_session.id,
        device_name=device.name,
        client_public_key=device.public_key,
        assigned_ip=vpn_session.assigned_ip,
        status=vpn_session.status.value,
        created_at=vpn_session.created_at,
        expires_at=vpn_session.expires_at,
        last_handshake=stats.last_handshake if stats else None,
        transfer_rx=stats.transfer_rx if stats else 0,
        transfer_tx=stats.transfer_tx if stats else 0,
    )


async def revoke_session(
    user: User,
    session_id: str,
    db: AsyncSession,
    wg_manager: WireGuardManager,
) -> SessionRevokeResponse:
    """Revoke a session: remove the WireGuard peer and mark the session revoked.

    Args:
        user: Authenticated user (must own the session).
        session_id: UUID of the session to revoke.
        db: Active database session.
        wg_manager: WireGuard manager to remove the peer from.

    Returns:
        SessionRevokeResponse confirming revocation.

    Raises:
        HTTPException 404: Session not found or not owned by this user.
        HTTPException 409: Session is already expired or revoked.
    """
    result = await db.execute(
        select(VPNSession, Device)
        .join(Device, VPNSession.device_id == Device.id)
        .where(VPNSession.id == session_id, VPNSession.user_id == user.id)
    )
    row = result.one_or_none()
    if row is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Session not found.",
        )

    vpn_session, device = row
    if vpn_session.status != SessionStatus.active:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Session is already {vpn_session.status.value}.",
        )

    try:
        await wg_manager.remove_peer(device.public_key)
    except WireGuardError as exc:
        logger.warning("Could not remove WireGuard peer %s: %s", device.public_key[:8], exc)

    vpn_session.status = SessionStatus.revoked
    vpn_session.revoked_at = datetime.now(tz=timezone.utc)
    await db.commit()

    logger.info("Revoked session %s for user %s", session_id, user.username)

    return SessionRevokeResponse(session_id=session_id, status="revoked")


async def list_devices(user: User, db: AsyncSession) -> DeviceListResponse:
    """List all devices registered by the authenticated user.

    Args:
        user: Authenticated user whose devices to retrieve.
        db: Active database session.

    Returns:
        DeviceListResponse containing all devices for the user.
    """
    result = await db.execute(
        select(Device)
        .where(Device.user_id == user.id)
        .order_by(Device.created_at.desc())
    )
    devices = result.scalars().all()

    items = [
        DeviceItem(
            device_id=d.id,
            name=d.name,
            public_key=d.public_key,
            created_at=d.created_at,
            last_active=d.last_active_at,
        )
        for d in devices
    ]
    return DeviceListResponse(devices=items)


async def _get_or_create_device(
    user: User,
    device_name: str,
    public_key: str,
    db: AsyncSession,
) -> Device:
    """Find an existing device by public key, or create a new one.

    If the public key already belongs to this user under a different name, the
    existing device record is returned unchanged to avoid name drift.

    Args:
        user: Owner of the device.
        device_name: Requested name for the device.
        public_key: WireGuard public key to look up or register.
        db: Active database session.

    Returns:
        Existing or newly created Device record.
    """
    result = await db.execute(
        select(Device).where(
            Device.user_id == user.id,
            Device.public_key == public_key,
        )
    )
    device = result.scalar_one_or_none()
    if device is not None:
        return device

    device = Device(user_id=user.id, name=device_name, public_key=public_key)
    db.add(device)
    await db.flush()
    return device
