#!/usr/bin/env bash
set -euo pipefail

# VPN Service with 2FA — VPS Setup Script
# Tested on Ubuntu 24.04 LTS (UpCloud)

DOMAIN="${1:-}"
ADMIN_USER="${2:-admin}"
ADMIN_PASS="${3:-}"
INSTALL_DIR="/opt/vpnservice"

usage() {
    echo "Usage: $0 <domain> [admin_user] [admin_password]"
    echo "  domain:         Your server domain (e.g., vpn.example.com) or IP"
    echo "  admin_user:     Admin username (default: admin)"
    echo "  admin_password: Admin password (will prompt if not provided)"
    exit 1
}

[[ -z "$DOMAIN" ]] && usage

if [[ -z "$ADMIN_PASS" ]]; then
    read -s -p "Enter admin password: " ADMIN_PASS
    echo
    read -s -p "Confirm admin password: " ADMIN_PASS2
    echo
    [[ "$ADMIN_PASS" != "$ADMIN_PASS2" ]] && echo "Passwords don't match" && exit 1
fi

echo "=== Installing Docker ==="
if ! command -v docker &>/dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
else
    echo "Docker already installed"
fi

echo "=== Installing WireGuard tools ==="
apt-get update -qq
apt-get install -y -qq wireguard-tools

echo "=== Enabling IP forwarding ==="
sysctl -w net.ipv4.ip_forward=1
grep -q "^net.ipv4.ip_forward=1" /etc/sysctl.conf || echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf

echo "=== Configuring firewall ==="
apt-get install -y -qq ufw
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw allow 51820/udp
ufw --force enable

echo "=== Creating application directory ==="
mkdir -p "$INSTALL_DIR/data"

echo "=== Generating secrets ==="
VPN_SECRET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || openssl rand -base64 32)
VPN_JWT_SECRET=$(openssl rand -base64 32)

echo "=== Writing .env file ==="
cat > "$INSTALL_DIR/.env" <<ENVEOF
# VPN Service Configuration — generated by setup.sh
VPN_SECRET_KEY=${VPN_SECRET_KEY}
VPN_JWT_SECRET=${VPN_JWT_SECRET}
VPN_ADMIN_USERNAME=${ADMIN_USER}
VPN_ADMIN_PASSWORD=${ADMIN_PASS}
VPN_WG_ENDPOINT=${DOMAIN}:51820
VPN_DOMAIN=${DOMAIN}
TLS_MODE=internal
ENVEOF

chmod 600 "$INSTALL_DIR/.env"

echo ""
echo "=== Setup complete ==="
echo "Next steps:"
echo "  1. Copy your project files:  rsync -avz src/ root@SERVER:${INSTALL_DIR}/"
echo "  2. SSH to server and start:  cd ${INSTALL_DIR} && docker compose --env-file .env up -d --build"
echo "  3. Check health:             curl -k https://${DOMAIN}/api/v1/health"
echo ""
echo "For production TLS, set TLS_MODE= (empty) in .env and point your domain DNS to this server."
echo "For self-signed (demo), keep TLS_MODE=internal."
